.TH man 8 "30 Jan 2022" "1.0" "wgen"
.SH NAME
wgen \- wordlist generator
.SH SYNOPSIS
wgen [OPTION]...
.SH DESCRIPTION
A simple wordlist generator written in C for Linux.

Mandatory arguments.

-o OUT 
    write generated wordlist to a file named OUT

-min MIN 
    set minimum word length to MIN (MIN must; be greater then or equal to 1, and less then or equal to MAX)

-max MAX 
    set maximum word length to MAX (MAX must; be greater then or equal to 1, and greater then or equal to MIN)

At least one argument from.

-d
    append [0-9] to the alphabet

-l
    append [a-z] to the alphabet

-L
    append [A-Z] to the alphabet

-s
    append [space] to the alphabet

-a "CHARACTERS"
    append "CHARACTERS" (a series of characters, with no space between them) to the alphabet, 
    note you may need to escape some special characters
.SH FORMAT
wgen -o OUT -min MIN -max MAX [-d, -l, -L, -s, -a]
.SH EXAMPLES
Generate all possible words of length five, with alphabet {0..9, $, ^}, and write results to a file name wordlist.txt.

wgen -o wordlist.txt -min 5 -max 5 -d -a "&^"
.SH BUGS
No known bugs.
.SH AUTHOR
Richard (https://github.com/r760)
